version: "3.8"

services:
  webservice:
    build:
      context: ./webservice
      dockerfile: Dockerfile
    container_name: webservice
    ports:
      - 8000:8000
    volumes:
      - ./webservice:/usr/src/app
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db