version: "3.8"

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - webclient
      - webservice
  webclient:
    build:
      context: ./webclient
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./webclient/src:/usr/src/app/src
    depends_on:
      - webservice
  webservice:
    build:
      context: ./webservice
      dockerfile: Dockerfile
    container_name: webservice
    ports:
      - 8000:8000
    volumes:
      - ./webservice:/usr/src/app
    environment:
      - MONGODB_URL=mongodb://mongo/?retryWrites=true&w=majority
      - MONGODB_DB=football
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db